sudo: required

language: python

services:
  - docker

before_install:
  - df -h
#  - docker pull jpata/cmssw:CMSSW_8_0_19_tth
#  - docker run --privileged -u 0 jpata/cmssw:CMSSW_8_0_19_tth ls /cvmfs/

script:
  - ls
